[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
evoting_program = "8FRU7VFhWedVur3jnDeNUVf1pLgaZY7ykH1UxMrYSVEe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = '../../wallet/keypair.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
